### PR TITLE
Manually read and set tag instead of relying on a pushed ref

### PR DESCRIPTION
**Pull request by holly-cummins**
Apparently the new tagging mechanism introduced in #18 [hasn’t worked](https://github.com/quarkiverse/antora-ui-quarkiverse/actions/runs/5259825834). 

```
Error undefined: No tag found in ref or input!
```

There’s [some discussion of this](https://github.com/orgs/community/discussions/26381), which suggests changing to have the workflow run on tag push. That’s a lot more workflows, so what would be ideal is if the action would output the tag name. That seems to be possible, so I've implemented an attempt at it.

### CODE REVIEW

**Comment by holly-cummins** [comment]
So this looks quite promising

image

... but the fact we have [two 'HEAD' releases](https://github.com/quarkiverse/antora-ui-quarkiverse/releases) is rather less good. It seems each tag generates a unique release, so the URL of the latest release is https://github.com/quarkiverse/antora-ui-quarkiverse/releases/download/v0.2.0/ui-bundle.zip. That's no good. I wonder if we'll have to live with using 'latest' as the tag and having the release tag not match the contents of the archive.
